wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.12
    start_time: 1657434978
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 51
      - 53
      - 55
      3:
      - 7
      4: 3.9.12
      5: 0.12.21
      6: 4.5.1
      8:
      - 3
      - 5
lr:
  desc: null
  value: 3.0e-05
model_name:
  desc: null
  value: google/bert_uncased_L-2_H-128_A-2
